// filtersData.js
export const locations = [
  "California",
  "Texas",
  "Arizona",
  "Florida",
  "Nevada",
  "Colorado",
  "Montana",
  "Oregon",
  "Georgia",
  "New York",
  "Washington",
  "Illinois",
  "Wisconsin",
  "Idaho",
];


export const specialties = [
  "Cardiology",
  "Pediatrics",
  "Dermatology",
  "Oncology",
  "ENT",
  "Family Medicine",
  "Orthopedics",
  "Psychiatry",
  "Dentistry",
  "Ophthalmology",
  "Urology",
  "Rheumatology",
  "Internal Medicine",
  "Nutrition",
  "Geriatrics",
  "Pulmonology",
  "Psychology",
  "Orthodontics",
  "Oral Surgery",
  "General Medicine",
  "Physical Therapy",
  "Chiropractic Care",
  "Pharmacy",
  "Veterinary Medicine",
  "Pet Surgery",
  "Dental Care",
  "Optometry",
  "LASIK Surgery",
  "Cosmetic Dentistry",
  "Health Supplements",
  "Sports Rehabilitation",
  "Obstetrics",
  "Gynecology",
  "Women's Health",
  "Counseling",
  "Addiction Treatment",
  "Spinal Manipulation",
  "Pain Relief",
  "Cosmetic Procedures",
  "Skin Cancer Treatment",
  "Sports Medicine",
  "Joint Replacement",
  "Adolescent Medicine",
  "Developmental Pediatrics",
  "Interventional Cardiology",
  "Electrophysiology",
  "Preventive Care",
  "Post-Surgical Recovery",
  "Mental Health Counseling",
  "Braces",
  "Invisalign",
];

export const services = [
  "Acne Treatment",
  "Alzheimer's Care",
  "Annual Physicals",
  "Anxiety Management",
  "Asthma Treatment",
  "Behavioral Assessments",
  "Birth Control Consultation",
  "Botox Injections",
  "Braces",
  "Braces Installation",
  "Cataract Surgery",
  "Chemotherapy",
  "Chronic Disease Management",
  "Clear Aligner Therapy",
  "Cognitive Behavioral Therapy",
  "Contact Lens Fitting",
  "Coronary Angioplasty",
  "Dental Cleaning",
  "Dental Implants",
  "Dermabrasion",
  "Developmental Screening",
  "Diabetes Management",
  "Echocardiogram",
  "Echocardiography",
  "Eye Exams",
  "Fitness Training",
  "Fracture Care",
  "Group Counseling",
  "Health Consultations",
  "Health Screenings",
  "ICD Insertion",
  "Immunizations",
  "Individual Therapy",
  "Injury Rehabilitation",
  "Knee Surgery",
  "Laser Hair Removal",
  "Manual Therapy",
  "Medical Supplies",
  "Medication Management",
  "Menopause Management",
  "Mohs Surgery",
  "Natural Supplements",
  "Newborn Care",
  "Nutritional Counseling",
  "Pain Management",
  "Pet Vaccinations",
  "Physical Exams",
  "Physical Therapy",
  "Prescription Filling",
  "Prescription Refills",
  "Primary Care",
  "Prostate Screening",
  "Psychiatric Evaluation",
  "Retainers",
  "Root Canal Treatment",
  "Skin Biopsy",
  "Skin Cancer Screening",
  "Spaying and Neutering",
  "Spinal Adjustment",
  "Sports Injury Treatment",
  "Strength Training",
  "Stress Management",
  "Substance Abuse Counseling",
  "Teeth Cleaning",
  "Teeth Whitening",
  "Tonsillectomy",
  "Vaccinations",
  "Well-child Visits",
  "Wisdom Tooth Extraction",
];
